#!/bin/bash

<< task 
deploy a app and automate the all to solve the task automated task
task

code_clone(){
	if [ ! -d "myfirstrepo" ]; then
	git clone https://github.com/shishirsri14/myfirstrepo.git
else
	echo "Repo is already exits"
	fi
}

install_requirement(){
	echo "Installing Dependences..."
	sudo apt update 
	sudo apt install nginx -y
}
start_nginx(){
	sudo systemctl start nginx 
}

echo "all service automatcally start tasking"

code_clone
install_requirement
start_nginx


echo "done done "



